-- Phase 1 schema. Portable between H2 (MODE=PostgreSQL) and PostgreSQL.

CREATE TABLE app_user (
    id             UUID PRIMARY KEY,
    version        BIGINT NOT NULL DEFAULT 0,
    email          VARCHAR(320) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    display_name   VARCHAR(120) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE refresh_token (
    id          UUID PRIMARY KEY,
    version     BIGINT NOT NULL DEFAULT 0,
    user_id     UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    family_id   UUID NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_token_family ON refresh_token (family_id);

-- Reference data: roles and governance modes are rows, not enums, so new ones need no code.
CREATE TABLE role (
    code  VARCHAR(32) PRIMARY KEY,
    name  VARCHAR(64) NOT NULL,
    rank  INT NOT NULL
);

CREATE TABLE governance_mode (
    code         VARCHAR(32) PRIMARY KEY,
    name         VARCHAR(64) NOT NULL,
    description  VARCHAR(500) NOT NULL
);

-- (governance_mode, action, role) -> scope. The single source of authorization truth.
CREATE TABLE permission_policy (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    governance_mode  VARCHAR(32) NOT NULL REFERENCES governance_mode (code),
    action           VARCHAR(48) NOT NULL,
    role_code        VARCHAR(32) NOT NULL REFERENCES role (code),
    scope            VARCHAR(16) NOT NULL,
    CONSTRAINT uk_permission_policy UNIQUE (governance_mode, action, role_code),
    CONSTRAINT ck_permission_policy_scope CHECK (scope IN ('ANY', 'OWN_UNIT'))
);

CREATE TABLE building (
    id               UUID PRIMARY KEY,
    version          BIGINT NOT NULL DEFAULT 0,
    name             VARCHAR(200) NOT NULL,
    address          VARCHAR(500),
    governance_mode  VARCHAR(32) NOT NULL REFERENCES governance_mode (code),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Location tree: adjacency list (parent_id) + materialized path (/rootId/.../ownId/) for subtree queries.
CREATE TABLE space (
    id           UUID PRIMARY KEY,
    version      BIGINT NOT NULL DEFAULT 0,
    building_id  UUID NOT NULL REFERENCES building (id) ON DELETE CASCADE,
    parent_id    UUID REFERENCES space (id) ON DELETE CASCADE,
    space_type   VARCHAR(32) NOT NULL,
    name         VARCHAR(200) NOT NULL,
    sort_order   INT NOT NULL DEFAULT 0,
    visibility   VARCHAR(16),
    path         VARCHAR(1024) NOT NULL,
    depth        INT NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_space_visibility CHECK (visibility IS NULL OR visibility IN ('COMMON', 'PRIVATE'))
);
CREATE INDEX ix_space_building ON space (building_id);
CREATE INDEX ix_space_parent ON space (parent_id);
CREATE INDEX ix_space_path ON space (path);

CREATE TABLE membership (
    id             UUID PRIMARY KEY,
    version        BIGINT NOT NULL DEFAULT 0,
    building_id    UUID NOT NULL REFERENCES building (id) ON DELETE CASCADE,
    user_id        UUID NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role_code      VARCHAR(32) NOT NULL REFERENCES role (code),
    unit_space_id  UUID REFERENCES space (id) ON DELETE SET NULL,
    status         VARCHAR(16) NOT NULL,
    expires_at     TIMESTAMP WITH TIME ZONE,
    revoked_at     TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_membership_building_user UNIQUE (building_id, user_id)
);
CREATE INDEX ix_membership_user ON membership (user_id);
