-- Built-in roles. rank: a member can never grant or modify a role ranked above their own.
INSERT INTO role (code, name, rank) VALUES
    ('TENANT',  'Tenant',  10),
    ('OWNER',   'Owner',   20),
    ('MANAGER', 'Manager', 30),
    ('ADMIN',   'Admin',   40);

INSERT INTO governance_mode (code, name, description) VALUES
    ('MANAGED', 'Managed', 'Only admins and managers edit the building structure and triage issues.'),
    ('OPEN',    'Open',    'Any invited member can edit the structure and add assets; owners can also triage.');

-- ---------- MANAGED preset ----------
INSERT INTO permission_policy (governance_mode, action, role_code, scope) VALUES
    ('MANAGED', 'BUILDING_VIEW',     'ADMIN',   'ANY'),
    ('MANAGED', 'BUILDING_VIEW',     'MANAGER', 'ANY'),
    ('MANAGED', 'BUILDING_VIEW',     'OWNER',   'ANY'),
    ('MANAGED', 'BUILDING_VIEW',     'TENANT',  'ANY'),
    ('MANAGED', 'BUILDING_SETTINGS', 'ADMIN',   'ANY'),
    ('MANAGED', 'STRUCTURE_EDIT',    'ADMIN',   'ANY'),
    ('MANAGED', 'STRUCTURE_EDIT',    'MANAGER', 'ANY'),
    ('MANAGED', 'ASSET_CREATE',      'ADMIN',   'ANY'),
    ('MANAGED', 'ASSET_CREATE',      'MANAGER', 'ANY'),
    ('MANAGED', 'ASSET_EDIT',        'ADMIN',   'ANY'),
    ('MANAGED', 'ASSET_EDIT',        'MANAGER', 'ANY'),
    ('MANAGED', 'ASSET_DELETE',      'ADMIN',   'ANY'),
    ('MANAGED', 'ASSET_DELETE',      'MANAGER', 'ANY'),
    ('MANAGED', 'ISSUE_REPORT',      'ADMIN',   'ANY'),
    ('MANAGED', 'ISSUE_REPORT',      'MANAGER', 'ANY'),
    ('MANAGED', 'ISSUE_REPORT',      'OWNER',   'ANY'),
    ('MANAGED', 'ISSUE_REPORT',      'TENANT',  'ANY'),
    ('MANAGED', 'ISSUE_TRIAGE',      'ADMIN',   'ANY'),
    ('MANAGED', 'ISSUE_TRIAGE',      'MANAGER', 'ANY'),
    ('MANAGED', 'CATALOG_EDIT',      'ADMIN',   'ANY'),
    ('MANAGED', 'CATALOG_EDIT',      'MANAGER', 'ANY'),
    ('MANAGED', 'MEMBER_INVITE',     'ADMIN',   'ANY'),
    ('MANAGED', 'MEMBER_INVITE',     'MANAGER', 'ANY'),
    ('MANAGED', 'MEMBER_INVITE',     'OWNER',   'OWN_UNIT'),
    ('MANAGED', 'MEMBER_MANAGE',     'ADMIN',   'ANY'),
    ('MANAGED', 'MEMBER_MANAGE',     'MANAGER', 'ANY'),
    ('MANAGED', 'MEMBER_MANAGE',     'OWNER',   'OWN_UNIT');

-- ---------- OPEN preset ----------
INSERT INTO permission_policy (governance_mode, action, role_code, scope) VALUES
    ('OPEN', 'BUILDING_VIEW',     'ADMIN',   'ANY'),
    ('OPEN', 'BUILDING_VIEW',     'MANAGER', 'ANY'),
    ('OPEN', 'BUILDING_VIEW',     'OWNER',   'ANY'),
    ('OPEN', 'BUILDING_VIEW',     'TENANT',  'ANY'),
    ('OPEN', 'BUILDING_SETTINGS', 'ADMIN',   'ANY'),
    ('OPEN', 'STRUCTURE_EDIT',    'ADMIN',   'ANY'),
    ('OPEN', 'STRUCTURE_EDIT',    'MANAGER', 'ANY'),
    ('OPEN', 'STRUCTURE_EDIT',    'OWNER',   'ANY'),
    ('OPEN', 'STRUCTURE_EDIT',    'TENANT',  'ANY'),
    ('OPEN', 'ASSET_CREATE',      'ADMIN',   'ANY'),
    ('OPEN', 'ASSET_CREATE',      'MANAGER', 'ANY'),
    ('OPEN', 'ASSET_CREATE',      'OWNER',   'ANY'),
    ('OPEN', 'ASSET_CREATE',      'TENANT',  'ANY'),
    ('OPEN', 'ASSET_EDIT',        'ADMIN',   'ANY'),
    ('OPEN', 'ASSET_EDIT',        'MANAGER', 'ANY'),
    ('OPEN', 'ASSET_EDIT',        'OWNER',   'ANY'),
    ('OPEN', 'ASSET_EDIT',        'TENANT',  'ANY'),
    ('OPEN', 'ASSET_DELETE',      'ADMIN',   'ANY'),
    ('OPEN', 'ASSET_DELETE',      'MANAGER', 'ANY'),
    ('OPEN', 'ASSET_DELETE',      'OWNER',   'ANY'),
    ('OPEN', 'ISSUE_REPORT',      'ADMIN',   'ANY'),
    ('OPEN', 'ISSUE_REPORT',      'MANAGER', 'ANY'),
    ('OPEN', 'ISSUE_REPORT',      'OWNER',   'ANY'),
    ('OPEN', 'ISSUE_REPORT',      'TENANT',  'ANY'),
    ('OPEN', 'ISSUE_TRIAGE',      'ADMIN',   'ANY'),
    ('OPEN', 'ISSUE_TRIAGE',      'MANAGER', 'ANY'),
    ('OPEN', 'ISSUE_TRIAGE',      'OWNER',   'ANY'),
    ('OPEN', 'CATALOG_EDIT',      'ADMIN',   'ANY'),
    ('OPEN', 'CATALOG_EDIT',      'MANAGER', 'ANY'),
    ('OPEN', 'CATALOG_EDIT',      'OWNER',   'ANY'),
    ('OPEN', 'MEMBER_INVITE',     'ADMIN',   'ANY'),
    ('OPEN', 'MEMBER_INVITE',     'MANAGER', 'ANY'),
    ('OPEN', 'MEMBER_INVITE',     'OWNER',   'OWN_UNIT'),
    ('OPEN', 'MEMBER_MANAGE',     'ADMIN',   'ANY'),
    ('OPEN', 'MEMBER_MANAGE',     'MANAGER', 'ANY'),
    ('OPEN', 'MEMBER_MANAGE',     'OWNER',   'OWN_UNIT');
