package com.condo.notification;

public enum NotificationType {
    ISSUE_REPORTED,
    ISSUE_STATUS_CHANGED,
    ISSUE_COMMENTED,
    ISSUE_MERGED,
    TASK_DUE,
    TASK_OVERDUE,
    BOOKING_REQUESTED,
    BOOKING_REVIEW_REMINDER,
    BOOKING_CONFIRMED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED
}
